#ifndef MODULES_CALCULATOR_COMPLEX_NUMBERS_INCLUDE_CALCULATOR_COMPLEX_NUMBERS_H_
#define MODULES_CALCULATOR_COMPLEX_NUMBERS_INCLUDE_CALCULATOR_COMPLEX_NUMBERS_H_
class CalculatorComplexNumbers
{
    private:
        int a;
    public:
    CalculatorComplexNumbers();
};

#endif //MODULES_CALCULATOR_COMPLEX_NUMBERS_INCLUDE_CALCULATOR_COMPLEX_NUMBERS_H_